<!-- resources/views/pdf/export-teachers.blade.php -->

<!DOCTYPE html>
<html>
<head>
    <title>Export Teachers</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 10px; /* Menambahkan padding di sekeliling body */
            page-break-inside: avoid;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header img {
            max-width: 100px;
        }
        .header h1, .header h2 {
            margin: 5px;
        }
        .table-wrapper {
            overflow-x: auto;
            margin: 0 0 20px 0; /* Menghapus padding horizontal untuk mencegah tumpang tindih */
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            table-layout: auto; /* Menyesuaikan lebar kolom otomatis */
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
            max-width: 150px; /* Membatasi lebar kolom */
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>SchoolSync High School</h1>
        <h2>List of Teachers</h2>
        <p>Date: {{ date('d-m-Y') }}</p>
    </div>
    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    <th>Nama Lengkap</th>
                    <th>Tanggal Bergabung</th>
                    <th>Nomor Telepon</th>
                    <th>Jenis Kelamin</th>
                    <th>Pengalaman</th>           
                </tr>
            </thead>
            <tbody>
                @foreach($teachers as $teacher)
                    <tr>
                        <td>{{ $teacher->full_name }}</td>
                        <td>{{ $teacher->join_date }}</td>
                        <td>{{ $teacher->phone_number }}</td>
                        <td>{{ $teacher->gender }}</td>
                        <td>{{ $teacher->experience }} years</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="footer">
        <p>Generated by SchoolSync</p>
    </div>
</body>
</html>
